#!/usr/bin/env bash
#
# setup.sh: hermes-dispatch interactive setup (the "Do It With Me" tier).
#
# Walks you through hardware detection, backend choice, model preset,
# config.yaml generation, desktop profiles, optional Obsidian and Tailscale,
# and a smoke test. Non-destructive: backs up an existing config.yaml, and never
# pulls models or runs `tailscale serve` without an explicit yes. Read it top to
# bottom; every external command it runs is printed first.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# --- pretty helpers ----------------------------------------------------------
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
info()  { printf '  \033[36m%s\033[0m\n' "$*"; }
warn()  { printf '  \033[33m%s\033[0m\n' "$*"; }
ok()    { printf '  \033[32m✓\033[0m %s\n' "$*"; }
rule()  { printf '\033[2m%s\033[0m\n' "────────────────────────────────────────────────────────"; }

ask() { # ask "Question" "default" -> echoes answer
  local q="$1" def="${2-}" ans
  if [ -n "$def" ]; then printf '  %s [%s]: ' "$q" "$def" >&2; else printf '  %s: ' "$q" >&2; fi
  read -r ans || true
  printf '%s' "${ans:-$def}"
}
yesno() { # yesno "Question" "Y|N" -> returns 0 for yes
  local q="$1" def="${2:-N}" ans
  ans="$(ask "$q (y/n)" "$def")"
  case "$ans" in [Yy]*) return 0 ;; *) return 1 ;; esac
}
have() { command -v "$1" >/dev/null 2>&1; }

# --- intro -------------------------------------------------------------------
bold "hermes-dispatch guided setup"
rule

# --- 1. detect hardware ------------------------------------------------------
OS="$(uname -s)"; ARCH="$(uname -m)"
PRESET="models-minimal.yaml"; TIER="minimal (one model)"
if [ "$OS" = "Darwin" ] && [ "$ARCH" = "arm64" ]; then
  MEM_GB=$(( $(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1073741824 ))
  PRESET="models-m4-apple-silicon.yaml"; TIER="Apple Silicon (${MEM_GB:-?} GB unified)"
elif [ "$OS" = "Linux" ] && have nvidia-smi; then
  PRESET="models-nvidia-24gb.yaml"; TIER="NVIDIA GPU (CUDA)"
fi
bold "1. Hardware"
info "Detected: $OS / $ARCH. Recommended preset: $TIER"
alt="$(ask "Use this preset? Enter a different examples/ file to override, or press enter" "$PRESET")"
PRESET="$alt"
[ -f "examples/$PRESET" ] || { warn "examples/$PRESET not found; falling back to models-minimal.yaml"; PRESET="models-minimal.yaml"; }
ok "Preset: examples/$PRESET"
rule

# --- 2. backend --------------------------------------------------------------
bold "2. Backend"
info "1) Ollama (local models)   2) Existing LiteLLM proxy   3) Cloud APIs"
BACKEND="$(ask "Choose backend" "1")"
case "$BACKEND" in
  2) info "Using an existing LiteLLM proxy. Make sure it serves the 8 aliases." ;;
  3) info "Cloud APIs. Consider examples/models-cloud.yaml; set provider keys in your env."
     if [ "$PRESET" != "models-cloud.yaml" ] && yesno "Switch preset to models-cloud.yaml?" "Y"; then PRESET="models-cloud.yaml"; ok "Preset: examples/$PRESET"; fi ;;
  *) BACKEND="1"; info "Using local Ollama." ;;
esac
rule

# --- 3. pull models (Ollama only) -------------------------------------------
if [ "$BACKEND" = "1" ]; then
  bold "3. Models"
  if have ollama; then
    info "Models named by examples/$PRESET:"
    # extract the model tags from the preset's models: block
    MODELS=$(awk '/^models:/{f=1;next} f&&/^[^ ]/{f=0} f&&/ollama_chat\//{
      match($0,/ollama_chat\/[^"]+/); print substr($0,RSTART+12,RLENGTH-12)}' "examples/$PRESET" | sort -u)
    echo "$MODELS" | sed 's/^/    - /'
    if yesno "Pull these now with ollama?" "Y"; then
      while IFS= read -r m; do [ -n "$m" ] && { info "ollama pull $m"; ollama pull "$m" || warn "pull failed: $m"; }; done <<< "$MODELS"
    else
      info "Skipped. Pull them later with: ollama pull <tag>"
    fi
  else
    warn "ollama not on PATH. Install from https://ollama.com, then pull the models above."
  fi
  rule
fi

# --- 4. optional integrations (collected before writing config) --------------
bold "4. Optional integrations"
OBSIDIAN_VAULT=""
if yesno "Enable Obsidian save-to-vault?" "N"; then
  OBSIDIAN_VAULT="$(ask "Absolute path to your vault" "")"
  [ -n "$OBSIDIAN_VAULT" ] && ok "Obsidian vault: $OBSIDIAN_VAULT" || warn "No path given. Leaving Obsidian disabled."
fi
TAILSCALE_HOST=""
TS_ENABLE=false
if yesno "Enable Tailscale mobile access?" "N"; then
  TS_ENABLE=true
  TAILSCALE_HOST="$(ask "Your device's tailnet name (optional, for docs)" "")"
fi
rule

# --- 5. generate config.yaml -------------------------------------------------
bold "5. Generate config.yaml"
if [ -f config.yaml ]; then
  cp -f config.yaml config.yaml.bak
  ok "Backed up existing config.yaml to config.yaml.bak"
fi
MODELS_BLOCK="$(awk '/^models:/{f=1} f{print} f&&/^$/{exit}' "examples/$PRESET")"
{
  echo "# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) from examples/$PRESET"
  echo "$MODELS_BLOCK"
  echo ""
  echo "litellm_url: \"http://localhost:4000\""
  echo "hermes_home: \"~/.hermes\""
  echo "hermes_profiles_dir: \"~/.hermes/profiles\""
  echo "hermes_artifacts_dir: \"~/.hermes/artifacts\""
  echo "obsidian_vault: \"$OBSIDIAN_VAULT\""
  echo "obsidian_cli: \"obsidian\""
  echo "server_host: \"0.0.0.0\""
  echo "server_port: 7777"
  echo "dispatch_router_model: \"pipeline\""
  echo "dispatch_enhancer_model: \"analyze\""
  echo "tailscale_hostname: \"$TAILSCALE_HOST\""
} > config.yaml
ok "Wrote config.yaml"
rule

# --- 6. desktop profiles -----------------------------------------------------
bold "6. Hermes desktop profiles"
if have hermes && yesno "Register a desktop profile per agent (bin/gen-profiles.sh)?" "Y"; then
  bin/gen-profiles.sh && ok "Profiles generated. Open with: hermes desktop"
else
  info "Skipped. Run later: bin/gen-profiles.sh"
fi
rule

# --- 7. tailscale walkthrough ------------------------------------------------
if [ "$TS_ENABLE" = true ]; then
  bold "7. Tailscale mobile"
  info "To serve a clean, port-free URL over your tailnet, run:"
  echo "      tailscale serve --bg --http=80 http://127.0.0.1:7777"
  if have tailscale && yesno "Run it now?" "N"; then
    tailscale serve --bg --http=80 http://127.0.0.1:7777 && ok "Tailscale serve configured." || warn "tailscale serve failed. See docs/tailscale-mobile.md"
  else
    info "Skipped. See docs/tailscale-mobile.md."
  fi
  rule
fi

# --- 8. smoke test -----------------------------------------------------------
bold "8. Smoke test"
if have hermes && yesno "Hit a sample agent (triage-router) with a tiny prompt?" "Y"; then
  info "./agents/triage-router/run.sh \"setup smoke test\""
  if OUT="$(./agents/triage-router/run.sh "setup smoke test" 2>&1)"; then
    ok "Agent responded:"; printf '      %s\n' "$OUT" | head -3
  else
    warn "Agent call failed. Check: LiteLLM up on :4000, key in ~/.hermes/.env, model pulled."
    warn "Inspect the command without calling a model: HERMES_DRY_RUN=1 ./agents/triage-router/run.sh test"
  fi
else
  info "Skipped. Try: ./agents/triage-router/run.sh \"We launch next week\""
fi
rule

# --- 9. summary --------------------------------------------------------------
bold "Done. Summary:"
ok "Preset:        examples/$PRESET"
ok "Backend:       $([ "$BACKEND" = 1 ] && echo Ollama || { [ "$BACKEND" = 2 ] && echo 'existing LiteLLM' || echo 'cloud APIs'; })"
ok "Config:        $REPO_ROOT/config.yaml"
[ -n "$OBSIDIAN_VAULT" ] && ok "Obsidian:      enabled ($OBSIDIAN_VAULT)" || info "Obsidian:      disabled (optional)"
[ "$TS_ENABLE" = true ]  && ok "Mobile:        Tailscale enabled. Bookmark http://<host>.<tailnet>.ts.net" || info "Mobile:        not configured (optional)"
echo
info "Run an agent:      ./agents/<name>/run.sh \"input\""
info "Mobile chat:       python3 dispatch/server.py   (http://localhost:7777)"
info "Pipelines:         bin/run-pipeline.sh gtm-pipeline \"brief\""
info "Docs:              docs/quickstart.md"
