#!/usr/bin/env sh
#
# bootstrap.sh: first-run config generation for the Docker stack.
#
# Generates the LiteLLM model_list config from environment variables, so the
# whole alias → model map is driven by docker/.env instead of a hand-written
# LiteLLM config. Run as the `bootstrap` service; writes into a shared volume
# the `litellm` service then reads.
#
# Env (see .env.example): LITELLM_MASTER_KEY, the MODEL_FAST/BALANCED/MAX tiers,
# optional MODEL_STRUCTURED/CODE/WRITING/REASONING roles (inherit a tier if unset),
# and optional OLLAMA_BASE (to point ollama_chat/* models at a host Ollama).
#
set -eu

CONFIG_OUT="${CONFIG_OUT:-/config/litellm.config.yaml}"
OLLAMA_BASE="${OLLAMA_BASE:-}"

emit_model() {
  _alias="$1"; _model="$2"
  printf '  - model_name: %s\n' "$_alias"
  printf '    litellm_params:\n'
  printf '      model: %s\n' "$_model"
  # Point local Ollama models at the host's Ollama if OLLAMA_BASE is set.
  case "$_model" in
    ollama_chat/*|ollama/*)
      [ -n "$OLLAMA_BASE" ] && printf '      api_base: %s\n' "$OLLAMA_BASE" ;;
  esac
}

# Tiers (required) with cloud defaults.
FAST="${MODEL_FAST:-openai/gpt-4o-mini}"
BALANCED="${MODEL_BALANCED:-openai/gpt-4o-mini}"
MAX="${MODEL_MAX:-anthropic/claude-3-5-sonnet-latest}"
# Task roles inherit their default tier when unset (the two-axis convention).
STRUCTURED="${MODEL_STRUCTURED:-$FAST}"
CODE="${MODEL_CODE:-$BALANCED}"
WRITING="${MODEL_WRITING:-$BALANCED}"
REASONING="${MODEL_REASONING:-$MAX}"

mkdir -p "$(dirname "$CONFIG_OUT")"
{
  echo "# Generated by docker/bootstrap.sh. Edit docker/.env, not this file."
  echo "model_list:"
  emit_model fast       "$FAST"
  emit_model balanced   "$BALANCED"
  emit_model max        "$MAX"
  emit_model structured "$STRUCTURED"
  emit_model code       "$CODE"
  emit_model writing    "$WRITING"
  emit_model reasoning  "$REASONING"
  echo ""
  echo "general_settings:"
  echo "  master_key: os.environ/LITELLM_MASTER_KEY"
} > "$CONFIG_OUT"

echo "bootstrap: wrote $CONFIG_OUT"
echo "bootstrap: tiers (fast balanced max) + roles (structured code writing reasoning)"
[ -n "$OLLAMA_BASE" ] && echo "bootstrap: ollama_chat/* models routed to $OLLAMA_BASE"
exit 0
