#!/usr/bin/env sh
#
# bootstrap.sh: first-run config generation for the Docker stack.
#
# Generates the LiteLLM model_list config from environment variables, so the
# whole alias → model map is driven by docker/.env instead of a hand-written
# LiteLLM config. Run as the `bootstrap` service; writes into a shared volume
# the `litellm` service then reads.
#
# Env (see .env.example): LITELLM_MASTER_KEY, the eight MODEL_<ALIAS> strings,
# and optionally OLLAMA_BASE (to point ollama_chat/* models at a host Ollama).
#
set -eu

CONFIG_OUT="${CONFIG_OUT:-/config/litellm.config.yaml}"
OLLAMA_BASE="${OLLAMA_BASE:-}"

emit_model() {
  _alias="$1"; _model="$2"
  printf '  - model_name: %s\n' "$_alias"
  printf '    litellm_params:\n'
  printf '      model: %s\n' "$_model"
  # Point local Ollama models at the host's Ollama if OLLAMA_BASE is set.
  case "$_model" in
    ollama_chat/*|ollama/*)
      [ -n "$OLLAMA_BASE" ] && printf '      api_base: %s\n' "$OLLAMA_BASE" ;;
  esac
}

mkdir -p "$(dirname "$CONFIG_OUT")"
{
  echo "# Generated by docker/bootstrap.sh. Edit docker/.env, not this file."
  echo "model_list:"
  emit_model classify "${MODEL_CLASSIFY:-openai/gpt-4o-mini}"
  emit_model chat     "${MODEL_CHAT:-openai/gpt-4o-mini}"
  emit_model review   "${MODEL_REVIEW:-anthropic/claude-3-5-haiku-latest}"
  emit_model code     "${MODEL_CODE:-anthropic/claude-3-5-sonnet-latest}"
  emit_model analyze  "${MODEL_ANALYZE:-openai/o4-mini}"
  emit_model pipeline "${MODEL_PIPELINE:-openai/gpt-4o-mini}"
  emit_model write    "${MODEL_WRITE:-openai/gpt-4o}"
  emit_model quality  "${MODEL_QUALITY:-anthropic/claude-3-5-sonnet-latest}"
  echo ""
  echo "general_settings:"
  echo "  master_key: os.environ/LITELLM_MASTER_KEY"
} > "$CONFIG_OUT"

echo "bootstrap: wrote $CONFIG_OUT"
echo "bootstrap: aliases → classify chat review code analyze pipeline write quality"
[ -n "$OLLAMA_BASE" ] && echo "bootstrap: ollama_chat/* models routed to $OLLAMA_BASE"
exit 0
